apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gcjobs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gcjobs
subjects:
  - kind: ServiceAccount
    name: jx-gcjobs
    namespace: {{ .Release.Namespace }}
