apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gcjobs
rules:
  - apiGroups:
      - jenkins.io
    resources:
      - environments
      - plugins
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - delete
      - list
